name: flutter_adaptive
description: A series of widgets and utilities that adapt to the current platform.

version: 1.0.0

homepage: https://github.com/zippa-pizza/flutter_adaptive
repository: https://github.com/zippa-pizza/flutter_adaptive

platforms:
  android:
  ios:
  web:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  assorted_layout_widgets: ^6.1.1
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  resolve_font_height: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
