name: flutter_adaptive
description: A series of widgets and utilities that adapt to the current platform.

version: 4.0.0

homepage: https://github.com/zippa-pizza/flutter_adaptive
repository: https://github.com/zippa-pizza/flutter_adaptive

platforms:
  android:
  ios:
  web:

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  adaptive_icons: ^1.4.0
  assorted_layout_widgets: ^7.0.0
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  resolve_font_height: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
